/*
|| Package & Package Body de la Tabla ACREENCIA_CICLO
*/

CREATE OR REPLACE 
PACKAGE       pr_acreencia_ciclo AS

FUNCTION N_IDACRE RETURN NUMBER;

PROCEDURE INSERT_AC ( cpAC IN OUT acreencia_ciclo%ROWTYPE  );

END PR_ACREENCIA_CICLO;
/

CREATE OR REPLACE 
PACKAGE BODY pr_acreencia_ciclo AS


FUNCTION N_IDACRE RETURN NUMBER IS

  nIdAcre NUMBER;

BEGIN

   SELECT sq_acreencia_ciclo.NEXTVAL
   INTO   nIdacre
   FROM   DUAL;

   RETURN ( nIdAcre ) ;

END N_IDACRE;

PROCEDURE INSERT_AC ( cpAC IN OUT acreencia_ciclo%ROWTYPE  ) IS

BEGIN

   cpAc.IdAcre := PR_ACREENCIA_CICLO.N_IDACRE;

  BEGIN
   INSERT INTO ACREENCIA_CICLO
           ( IDACRE, NUMACRE,
             STSACRE, FECSTS,
             STSACRENVO, FECSTSNVO,
             TIPOACRE, CODMONEDA,
             MTOACRELOCAL, MTOACREMONEDA, FECVENCACRE,
             SLDOACRELOCAL, SLDOACREMONEDA,
             CODINTERLIDER, TIPOID, NUMID, DVID,
             IDEFACT, DPTOEMI, CODCONDCOBRO, FECNOTIF,
             CODCIA,
             TIPODML, CODUSRDML, FECDML )
   VALUES  ( cpAC.IDACRE, cpAC.NUMACRE,
             cpAC.STSACRE, cpAC.FECSTS,
             cpAC.STSACRENVO, cpAC.FECSTSNVO,
             cpAC.TIPOACRE, cpAC.CODMONEDA,
             cpAC.MTOACRELOCAL, cpAC.MTOACREMONEDA, cpAC.FECVENCACRE,
             cpAC.SLDOACRELOCAL, cpAC.SLDOACREMONEDA,
             cpAC.CODINTERLIDER, cpAC.TIPOID, cpAC.NUMID, cpAC.DVID,
             cpAC.IDEFACT, cpAC.DPTOEMI, cpAC.CODCONDCOBRO,
             cpAC.FECNOTIF,
             cpAC.CODCIA,
             cpAC.TIPODML, NVL(TRIM(cpAC.CODUSRDML),USER), NVL(cpAC.FECDML,SYSDATE) );
   EXCEPTION
     WHEN OTHERS THEN
       RAISE_APPLICATION_ERROR(-20100,' NUMACRE '||cpAC.NUMACRE||' '||SQLERRM);
   END;


END INSERT_AC;

END PR_ACREENCIA_CICLO;
/

