/*
|| Trigger TRG_ACREENCIA_CICLO en la Tabla ACREENCIA_CIA
*/

CREATE OR REPLACE TRIGGER trg_acreencia_ciclo
 AFTER
  INSERT OR DELETE OR UPDATE
 ON acreencia_cia
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
DECLARE

  cRowAC ACREENCIA_CICLO%ROWTYPE := NULL;

BEGIN

 IF INSERTING THEN
    cRowAC.TIPODML := 'I';

 ELSIF UPDATING THEN

    cRowAC.TIPODML := 'U';

 ELSIF DELETING THEN

    cRowAC.TIPODML := 'D';

    cRowAC.NUMACRE   := :OLD.Numacre;    cRowAC.STSACRE:= :OLD.STSACRE;   cRowAC.FECSTS:= :OLD.FECSTS;     cRowAC.STSACRENVO := :OLD.STSACRE;
    cRowAC.FECSTSNVO := :OLD.FECSTS;  cRowAC.TIPOACRE:= :OLD.TIPOACRE; cRowAC.CODMONEDA:= :OLD.CODMONEDA;  cRowAC.MTOACRELOCAL:= :OLD.MTOACRELOCAL;
    cRowAC.MTOACREMONEDA:= :OLD.MTOACREMONEDA;  cRowAC.FECVENCACRE:= :OLD.FECVENCACRE;
    cRowAC.SLDOACRELOCAL:= :OLD.SLDOACRELOCAL;  cRowAC.SLDOACREMONEDA:= :OLD.SLDOACREMONEDA;
    cRowAC.CODINTERLIDER:= :OLD.CODINTERLIDER;   cRowAC.TIPOID:= :OLD.TIPOID; cRowAC.NUMID:= :OLD.NUMID; cRowAC.DVID:= :OLD.DVID;
    cRowAC.IDEFACT:= :OLD.IDEFACT; cRowAC.DPTOEMI:= :OLD.DPTOEMI; cRowAC.CODCONDCOBRO:= :OLD.CODCONDCOBRO;
    cRowAC.FECNOTIF:= :OLD.FECNOTIF;
    cRowAC.CODCIA:= :OLD.CODCIA;

 END IF;

 IF INSERTING OR UPDATING THEN

    cRowAC.NUMACRE   := :NEW.Numacre;    cRowAC.STSACRE:= :NEW.STSACRE;   cRowAC.FECSTS:= :NEW.FECSTS;        cRowAC.STSACRENVO := :NEW.STSACRE;
    cRowAC.FECSTSNVO := :NEW.FECSTS;  cRowAC.TIPOACRE:= :NEW.TIPOACRE; cRowAC.CODMONEDA:= :NEW.CODMONEDA;  cRowAC.MTOACRELOCAL:= :NEW.MTOACRELOCAL;
    cRowAC.MTOACREMONEDA:= :NEW.MTOACREMONEDA;  cRowAC.FECVENCACRE:= :NEW.FECVENCACRE;
    cRowAC.SLDOACRELOCAL:= :NEW.SLDOACRELOCAL;  cRowAC.SLDOACREMONEDA:= :NEW.SLDOACREMONEDA;
    cRowAC.CODINTERLIDER:= :NEW.CODINTERLIDER;   cRowAC.TIPOID:= :NEW.TIPOID; cRowAC.NUMID:= :NEW.NUMID; cRowAC.DVID:= :NEW.DVID;
    cRowAC.IDEFACT:= :NEW.IDEFACT; cRowAC.DPTOEMI:= :NEW.DPTOEMI; cRowAC.CODCONDCOBRO:= :NEW.CODCONDCOBRO;
    cRowAC.FECNOTIF:= :NEW.FECNOTIF;
    cRowAC.CODCIA:= :NEW.CODCIA;
 END IF;

  PR_ACREENCIA_CICLO.INSERT_AC ( cRowAC );

EXCEPTION
  WHEN OTHERS THEN
  RAISE_APPLICATION_ERROR(-20100,'Numcare '||:NEW.Numacre||' '||sqlerrm);
END;
/


-- End of DDL Script for Trigger ACSEL.TRG_ACREENCIA_CICLO

